version: '3.8'
services:
  user-golang-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5000:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
